user:
  email:
    max_length: 255
  password:
    min_length: 6
  phone:
    min_length: 10
    max_length: 15
  avatar-size:
    max_size: 80
    min_size: 50
  gender:
    female: 0
    male: 1
per_page:
  default: 6
  manage_booking: 5
